version: "3.9"
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-oceanbio}:${POSTGRES_PASSWORD:-oceanbio123}@db:5432/${POSTGRES_DB:-oceanbio}
      - POSTGRES_USER=${POSTGRES_USER:-oceanbio}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-oceanbio123}
      - POSTGRES_DB=${POSTGRES_DB:-oceanbio}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - SECRET_KEY=${SECRET_KEY:-your-super-secret-key-change-in-production-123456789}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ENVIRONMENT=production
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
  db:
    image: postgis/postgis:16-3.4
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-oceanbio}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-oceanbio123}
      - POSTGRES_DB=${POSTGRES_DB:-oceanbio}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-oceanbio}"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
