name: Ocean-Bio Platform CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          
      - name: Set up environment
        run: |
          echo "SECRET_KEY=test-secret-key-for-ci" > backend/.env
          echo "DATABASE_URL=sqlite:///./test.db" >> backend/.env
          echo "ALGORITHM=HS256" >> backend/.env
          echo "ACCESS_TOKEN_EXPIRE_MINUTES=30" >> backend/.env
          
      - name: Validate imports
        working-directory: backend
        env:
          PYTHONPATH: .
        run: |
          python -c "from app.core.exceptions import DatabaseError, AuthenticationError, ValidationError; print('✅ All exception classes imported successfully')"
          python -c "from app.core.security import get_password_hash, verify_password; print('✅ Security module imported successfully')"
          python -c "from app.main import app; print('✅ Main application imported successfully')"
          
      - name: Run import validation tests
        working-directory: backend
        env:
          PYTHONPATH: .
        run: |
          pytest tests/test_imports.py -v
          
      - name: Run platform health check
        working-directory: backend
        env:
          PYTHONPATH: .
        run: |
          python -c "print('🌊 Ocean-Bio Platform Health Check'); from app.main import app; print('✅ Platform loaded successfully!')"
          
      - name: Display platform status
        run: |
          echo "🎉 Ocean-Bio Platform Status: OPERATIONAL"
          echo "✅ All core modules validated successfully"
          echo "🚀 Ready for marine research operations!"
